# Generated by Django 4.1.1 on 2022-12-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libros.country'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(verbose_name='Año publicacion'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre_categoria'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre_Pais'),
        ),
    ]
