# Generated by Django 4.1.1 on 2022-12-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_remove_author_id_alter_author_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
    ]
