# Generated by Django 4.1.1 on 2022-12-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre autor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID_Categoria')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID_Cuidad')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre_Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre_Libro')),
                ('year', models.DateField(verbose_name='Año publicacion')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('category', models.ManyToManyField(to='app.category', verbose_name='Categorias')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
